# brownie-config.yml
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - hifi-finance/prb-math@2.4.1
  - uniswap/v2-core@1.0.1
  - uniswap/solidity-lib@4.0.0-alpha
  - BongaBeraCapital/bera-utils@0.0.1-alpha

compiler:
  solc:
    version: 0.8.10
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'
      - '@hifi-finance/prb-math=hifi-finance/prb-math@2.4.1'
      - '@uniswap/v2-core=uniswap/v2-core@1.0.1'
      - '@uniswap/lib=uniswap/solidity-lib@4.0.0-alpha'
      - '@bonga-bera-capital/bera-utils=BongaBeraCapital/bera-utils@0.0.1-alpha'

networks:
  default: development
  development:
    cmd: ganache-cli
    cmd_settings:
      port: 8545
      gas_limit: 9721975
      default_balance: 10000 ether
      accounts: 150
      evm_version: istanbul
      mnemonic: brownie
